<?php

/**
 * @file
 * Contains hooks and other things module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_create_access().
 *
 * @see: hook_entity_access().
 */
function entity_limit_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  $result = TRUE;
  if (!empty($context['entity_type_id'])) {
    $result = \Drupal::service('entity_limit.inspector')->checkEntityLimits(
      $context['entity_type_id'],
      $entity_bundle,
      $account
    );
  }

  return ($result) ? AccessResult::neutral() : AccessResult::forbidden();
}
