<?php

/**
 * @file
 * Contains hooks and other things module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_limit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.entity_limit':
      $output = file_get_contents(drupal_get_path('module', 'entity_limit') . '/README.md');
      return $output;
  }
}

/**
 * Implements hook_entity_create_access().
 *
 * @see: hook_entity_access().
 */
function entity_limit_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  $result = TRUE;
  if (!empty($context['entity_type_id'])) {
    $result = \Drupal::service('entity_limit.inspector')->checkEntityLimitAccess(
      $context['entity_type_id'],
      $entity_bundle,
      $account
    );
  }

  return ($result) ? AccessResult::neutral() : AccessResult::forbidden();
}
